from acies.core.msg import AciesMsg

# x = AciesMsg.new_array_msg([1, 2, 3], 'ns/n/ctl', {'key': 'value'}, 'i16')
# print(x)
# print(x.timestamp)
# print(x.reply_to)
# print(x.get_payload())
# print(x.get_metadata())
# x_bytes = x.to_bytes()
# print(x_bytes)
# print(AciesMsg.from_bytes(x_bytes))
# print()

# x = AciesMsg.new_array_msg([1, 2, 3], 'ns/n/ctl', {'key': 'value'}, 'i32')
# print(x)
# print(x.timestamp)
# print(x.reply_to)
# print(x.get_payload())
# print(x.get_metadata())
# x_bytes = x.to_bytes()
# print(x_bytes)
# print(AciesMsg.from_bytes(x_bytes))
# print()

# x = AciesMsg.new_array_msg([1, 2, 3], 'ns/n/ctl', {'key': 'value'}, 'i64')
# print(x)
# print(x.timestamp)
# print(x.reply_to)
# print(x.get_payload())
# print(x.get_metadata())
# x_bytes = x.to_bytes()
# print(x_bytes)
# print(AciesMsg.from_bytes(x_bytes))
# print()

# x = AciesMsg.new_array_msg([1.0, 2.0, 3.0], 'ns/n/ctl', {'key': 'value'}, 'f64')
# print(x)
# print(x.timestamp)
# print(x.reply_to)
# print(x.get_payload())
# print(x.get_metadata())
# x_bytes = x.to_bytes()
# print(x_bytes)
# print(AciesMsg.from_bytes(x_bytes))
# print()

# x = AciesMsg.new_heartbeat('ns/n/ctl', {'key': 'value'})
# print(x)
# print(x.timestamp)
# print(x.reply_to)
# print(x.get_payload())
# print(x.get_metadata())
# x_bytes = x.to_bytes()
# print(x_bytes)
# print(AciesMsg.from_bytes(x_bytes))
# print()

# x = AciesMsg.new_ctl_msg('get', 'ns/n/ctl', {'key': 'value'})
# print(x)
# print(x.timestamp)
# print(x.reply_to)
# print(x.get_payload())
# print(x.get_metadata())
# x_bytes = x.to_bytes()
# print(x_bytes)
# print(AciesMsg.from_bytes(x_bytes))
# print()

x = AciesMsg.new_json_msg('ns/n/ctl', {'key': 'value'})
print(x)
print(x.timestamp)
print(x.reply_to)
print(x.get_payload())
print(x.get_metadata())
x_bytes = x.to_bytes()
print(x_bytes)
print(AciesMsg.from_bytes(x_bytes))
print()
